### ISSUE TITLE
kubeip not work with GKE 1.12.6 single node?

### ISSUE THREAD

**Issue by remoe** [doitintl/kubeip#46]
I try to setup kubeip on a single node (one node pool with one node) cluster. After I apply the configuration the node goes in the "NotReady" state. The node still stay in this state after deleting the kubeip deployment.

**Comment by avivl** [comment]
@remoe Kubeip will not work if there is only one node

**Comment by yra-wtag** [comment]
@avivl can you please explain a bit about why it wont work in a one node cluster. Is this a limitation of the current software and can be improved or an Architectural Decision that can not be fixed. 

Basically my question is regarding how it handles dynamic situations in the Kubernetes cluster for example upgrading Kubernetes version, Autoscaling etc. Another question is does it work well with existing clusters with already assigned ips? I am currently testing it on a new cluster.

**Comment by spark2ignite** [comment]
@yra-wtag KubeIP was designed for situations when you have multiple nodes in your GKE cluster but you want outgoing traffic to originate from a specific node or nodes. If your cluster has only one node, it means all your outgoing traffic will originate from this node and KubeIP will not be required. Make sense?

**Comment by yra-wtag** [comment]
> If your cluster has only one node, it means all your outgoing traffic will originate from this node and KubeIP will not be required. Make sense?
@spark2ignite 
Well if you have auto-scaling then you can have 1 to as many you like nodes. These nodes are created automatically, so how does kubeip handle this situation. 
The fact is the cluster does not have a fixed amount of nodes, it might have 1 to 5 nodes depending on the load of the service. So in our situation, KubeIP needs to assign static IP in a dynamic situation. Is it possible? currently or after some code change?

**Comment by spark2ignite** [comment]
@eranchetz can you please look into this?

**Comment by eranchetz** [comment]
I just deployed a single node cluster and kubeip according to the README, the machine ip changed a few seconds after, so it seems it does work with a single instance. 

@yra-wtag / @remoe can you please provide instruction on how to reproduce the issue?

**Comment by remoe** [comment]
I don't have this environment anymore. But I wonder how this should work, because in the docs it has:

```We recommend that KUBEIP_NODEPOOL should NOT be the same as KUBEIP_SELF_NODEPOOL```

So, when you have a one node nodepool you can't have two nodepools.

**Comment by eranchetz** [comment]
@remoe In my case I set the same node pool for both even though it is not recommended (which makes perfect sense). But it works nonetheless.

**Comment by remoe** [comment]
@eranchetz , I've also tried this in the past. But I had still the same issue. Which GKE version you have used?

**Comment by eranchetz** [comment]
@remoe I now see I used 1.11.8-gke.6, 
I'll create a new cluster and try again with 1.12.6.

**Comment by eranchetz** [comment]
@remoe OK, I was able to reproduce the issue with 1.12.6-gke.10, but, after a few seconds the node changed back to the "Ready" state, Any chance you can reproduce the issue and send me the details, I will try to follow your instructions.

**Comment by yra-wtag** [comment]
@eranchetz i have been able to reproduce the issue on 1.12.7-gke.10 ; As you have said previously the node indeed went back to `Ready` state. However i have tried twice it did not change IP after half an hour.

This is how the process worked 
1. I followed the instructions on a g1-small (1 vCPU, 1.7 GB memory) node, regarding ip address, service account
2. As every other node it starts with a default External Ip
3. Then i deployed using `kubectl apply -f deploy/.`
It got stuck in the unknown state indefinitely.

**Comment by eranchetz** [comment]
@yra-wtag , Ok, I will try to reproduce it myself with the same parameters and update.
thanks 👍

**Comment by eranchetz** [comment]
@yra-wtag I was still unable to reproduce with your parameters.
In case you reproduce it again, can you please share the output of:
```bash
kubectl logs `kubectl get pods -n kube-system -oname -lapp=kubeip` -n kube-system
```
Thanks again

**Comment by yra-wtag** [comment]
> @yra-wtag I was still unable to reproduce with your parameters.
> In case you reproduce it again, can you please share the output of:
> 
> ```shell
> kubectl logs `kubectl get pods -n kube-system -oname -lapp=kubeip` -n kube-system
> ```
> 
> Thanks again

@eranchetz thanks for the reply, unfortunately there is no logs. I think kubernetes lost connection to this node.

**Comment by remoe** [comment]
The reason why kube-ip can not run on a single-node cluster is because kube-ip changes the IP on the node running on the kube-ip:

https://github.com/doitintl/kubeip/blob/master/pkg/kipcompute/compute.go#L114

**Comment by remoe** [comment]
@yra-wtag , can you please try with this PR https://github.com/doitintl/kubeip/pull/56 ? It was the first time that kube-ip works for me ;)

**Comment by yra-wtag** [comment]
> @yra-wtag , can you please try with this PR #56 ? It was the first time that kube-ip works for me ;)
> 
> ```
>   KUBEIP_LABELKEY: "kubeip"
>   KUBEIP_LABELVALUE: "gke1"
>   KUBEIP_NODEPOOL: "pool1"
>   KUBEIP_FORCEASSIGNMENT: "true"
>   KUBEIP_ADDITIONALNODEPOOLS: ""
>   KUBEIP_TICKER: "5"
>   KUBEIP_ALLNODEPOOLS: "false"
>   KUBEIP_SELF_NODEPOOL: "small"
> ```
 Yeah we are already using that.
